=== edouard-lopez/coronavirus-policies-timeline/src/types/Event.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "required": ["entity", "published_date", "tags", "title", "url", "region"],
    "definitions": {
      "Entity": {
        "enum": [
          "academic",
          "company",
          "government",
          "health-organization",
          "individual",
          "international-organization",
          "newspaper"
        ],
        "type": "string"
      },
      "Tag": {
        "enum": [
          "announcement",
          "aviation",
          "bed",
          "behavior",
          "comparison",
          "copyright",
          "dataviz",
          "democracy",
          "distribution",
          "DIY",
          "drug",
          "economy",
          "easing",
          "first-case",
          "futurology",
          "hand-sanitizer",
          "health-care",
          "mask",
          "order",
          "pledge",
          "respirator",
          "restriction",
          "rule-change",
          "shipping",
          "shortage",
          "stay-at-home",
          "testing",
          "treatment",
          "triage",
          "turnaround",
          "virus"
        ]
      },
      "Region": {
        "enum": [
          "Europe",
          "Asia",
          "Africa",
          "North America",
          "South America",
          "World",
          "Afghanistan",
          "Albania",
          "Algeria",
          "Andorra",
          "Angola",
          "Antigua and Barbuda",
          "Argentina",
          "Armenia",
          "Australia",
          "Austria",
          "Azerbaijan",
          "Bahamas",
          "Bahrain",
          "Bangladesh",
          "Barbados",
          "Belarus",
          "Belgium",
          "Belize",
          "Benin",
          "Bhutan",
          "Bolivia",
          "Bosnia and Herzegovina",
          "Botswana",
          "Brazil",
          "Brunei",
          "Bulgaria",
          "Burkina Faso",
          "Burma",
          "Burundi",
          "Cabo Verde",
          "Cambodia",
          "Cameroon",
          "Canada",
          "Central African Republic",
          "Chad",
          "Chile",
          "China",
          "Colombia",
          "Congo (Brazzaville)",
          "Congo (Kinshasa)",
          "Costa Rica",
          "Cote d'Ivoire",
          "Croatia",
          "Cuba",
          "Cyprus",
          "Czechia",
          "Denmark",
          "Diamond Princess",
          "Djibouti",
          "Dominica",
          "Dominican Republic",
          "Ecuador",
          "Egypt",
          "El Salvador",
          "Equatorial Guinea",
          "Eritrea",
          "Estonia",
          "Eswatini",
          "Ethiopia",
          "Fiji",
          "Finland",
          "France",
          "Gabon",
          "Gambia",
          "Georgia",
          "Germany",
          "Ghana",
          "Greece",
          "Grenada",
          "Guatemala",
          "Guinea",
          "Guinea-Bissau",
          "Guyana",
          "Haiti",
          "Holy See",
          "Honduras",
          "Hungary",
          "Iceland",
          "India",
          "Indonesia",
          "Iran",
          "Iraq",
          "Ireland",
          "Israel",
          "Italy",
          "Jamaica",
          "Japan",
          "Jordan",
          "Kazakhstan",
          "Kenya",
          "Korea South",
          "Kosovo",
          "Kuwait",
          "Kyrgyzstan",
          "Laos",
          "Latvia",
          "Lebanon",
          "Liberia",
          "Libya",
          "Liechtenstein",
          "Lithuania",
          "Luxembourg",
          "MS Zaandam",
          "Madagascar",
          "Malawi",
          "Malaysia",
          "Maldives",
          "Mali",
          "Malta",
          "Mauritania",
          "Mauritius",
          "Mexico",
          "Moldova",
          "Monaco",
          "Mongolia",
          "Montenegro",
          "Morocco",
          "Mozambique",
          "Namibia",
          "Nepal",
          "Netherlands",
          "New Zealand",
          "Nicaragua",
          "Niger",
          "Nigeria",
          "North Macedonia",
          "Norway",
          "Oman",
          "Pakistan",
          "Panama",
          "Papua New Guinea",
          "Paraguay",
          "Peru",
          "Philippines",
          "Poland",
          "Portugal",
          "Qatar",
          "Romania",
          "Russia",
          "Rwanda",
          "Saint Kitts and Nevis",
          "Saint Lucia",
          "Saint Vincent and the Grenadines",
          "San Marino",
          "Sao Tome and Principe",
          "Saudi Arabia",
          "Senegal",
          "Serbia",
          "Seychelles",
          "Sierra Leone",
          "Singapore",
          "Slovakia",
          "Slovenia",
          "Somalia",
          "South Africa",
          "South Sudan",
          "Spain",
          "Sri Lanka",
          "Sudan",
          "Suriname",
          "Sweden",
          "Switzerland",
          "Syria",
          "Taiwan*",
          "Tanzania",
          "Thailand",
          "Timor-Leste",
          "Togo",
          "Trinidad and Tobago",
          "Tunisia",
          "Turkey",
          "USA",
          "Uganda",
          "Ukraine",
          "United Arab Emirates",
          "United Kingdom",
          "Uruguay",
          "Uzbekistan",
          "Venezuela",
          "Vietnam",
          "West Bank and Gaza",
          "Western Sahara",
          "Zambia",
          "Zimbabwe"
        ]
      }
    },
    "properties": {
      "entity": {
        "$ref": "#/items/definitions/Entity"
      },
      "published_date": {
        "type": "string"
      },
      "tags": {
        "items": {
          "$ref": "#/items/definitions/Tag",
          "type": "string"
        },
        "type": "array"
      },
      "title": {
        "type": "string"
      },
      "url": {
        "type": "string"
      },
      "region": {
        "type": "string",
        "$ref": "#/items/definitions/Region"
      }
    },
    "type": "object"
  }
}

=== edouard-lopez/coronavirus-policies-timeline/src/data/events.json
[
  {
    "title": "The first case of someone in China suffering from Covid-19",
    "url": "https://www.scmp.com/news/china/society/article/3074991/coronavirus-chinas-first-confirmed-covid-19-case-traced-back",
    "published_date": "2019-11-17T00:00:00+00:00",
    "entity": "government",
    "tags": ["virus"],
    "region": "World"
  },
  {
    "title": "Coronavirus : l’Europe suspend la règle poussant les avions à voler vides",
    "url": "https://reporterre.net/Coronavirus-l-Europe-suspend-la-regle-poussant-les-avions-a-voler-vides",
    "published_date": "2020-03-11",
    "entity": "government",
    "tags": ["rule-change", "aviation"],
    "region": "Europe"
  },
  {
    "title": "Canada to bar entry for most foreigners",
    "url": "https://www.bbc.com/news/world-us-canada-51861980",
    "published_date": "2020-03-16T21:12:18+00:00",
    "entity": "government",
    "tags": ["announcement", "restriction", "aviation"],
    "region": "Canada"
  },
  {
    "title": "Chinese scientists identify the ‘Wuhan Virus’. Screening continues on Thai-bound flights.",
    "url": "https://thethaiger.com/hot-news/tourism/chinese-scientists-identify-the-wuhan-virus-screening-continues-on-thai-bound-flights",
    "published_date": "2020-01-09T12:46:52+00:00",
    "entity": "government",
    "tags": ["announcement", "first-case"],
    "region": "China"
  },
  {
    "title": "Coronavirus: L'UE désapprouve la décision unilatérale américaine sur les voyages",
    "url": "https://www.boursorama.com/actualite-economique/actualites/coronavirus-l-ue-desapprouve-la-decision-unilaterale-americaine-sur-les-voyages-2724b69da901aefd1b83f72df327dec5",
    "published_date": "2020-03-12T13:32:03+0100",
    "entity": "government",
    "tags": ["aviation", "restriction"],
    "region": "Europe"
  },
  {
    "title": "Pénurie de masques : les autorités n’ont pas vu plus loin que le bout de leur nez",
    "url": "https://www.liberation.fr/france/2020/03/03/penurie-de-masques-les-autorites-n-ont-pas-vu-plus-loin-que-le-bout-de-leur-nez_1780489",
    "published_date": "2020-03-03T21:06:04",
    "entity": "government",
    "tags": ["announcement", "order", "mask"],
    "region": "France"
  },
  {
    "title": "Coronavirus en France : des écoles fermées, les rassemblements de plus de 1 000 personnes interdits",
    "url": "https://www.sudouest.fr/2020/03/08/coronavirus-7294562-10861.php",
    "published_date": "2020-03-08",
    "entity": "government",
    "tags": ["restriction"],
    "region": "France"
  },
  {
    "title": "\"Force majeure\", télétravail, relocalisations envisagées… Les mesures du gouvernement pour les entreprises et les salariés face au Covid-19",
    "url": "https://www.francetvinfo.fr/sante/maladie/coronavirus/coronavirus-le-gouvernement-annonce-des-mesures-pour-les-entreprises-et-les-salaries_3845133.html",
    "published_date": "2020-02-28T14:38:27+01:00",
    "entity": "government",
    "tags": ["rule-change"],
    "region": "France"
  },
  {
    "title": "Coronavirus : Macron annonce la fermeture de tous les établissements scolaires à partir de lundi",
    "url": "https://www.lemonde.fr/planete/live/2020/03/12/suspension-des-voyages-aux-etats-unis-etat-d-alerte-en-france-la-crise-du-coronavirus-en-direct_6032730_3244.html",
    "published_date": "2020-03-12T08:39:30+00:00",
    "entity": "government",
    "tags": ["announcement", "restriction"],
    "region": "France"
  },
  {
    "title": "Elections municipales : que se passerait-il en cas de report du second tour ?",
    "url": "https://www.lemonde.fr/politique/article/2020/03/15/municipales-que-se-passerait-il-en-cas-de-report-du-second-tour_6033152_823448.html",
    "published_date": "2020-03-15T12:59:02+00:00",
    "entity": "newspaper",
    "tags": ["futurology", "restriction", "democracy"],
    "region": "France"
  },
  {
    "title": "Témoignage inquiétant d'un médecin : les hôpitaux ne dépistent plus pour des raisons économiques.",
    "url": "https://www.lemondemoderne.media/covid-19/?fbclid=IwAR1wI86iPDbQkalxLxglOV2AQQpAw-1_JjC7G8nUVn7_HAZb57KOqNjDxk8",
    "published_date": "2020-03-13T17:20:28+00:00",
    "entity": "newspaper",
    "tags": ["testing", "restriction", "economy"],
    "region": "France"
  },
  {
    "title": "Affluence des grands jours au Marché d’Aligre à Paris malgré les mesures et consignes annoncées hier soir. #CoronavirusFrance #COVIDー19",
    "url": "https://twitter.com/RemyBuisine/status/1239161728858042371?s=20",
    "published_date": "2020-03-15T13:09:00+01:00",
    "entity": "individual",
    "tags": ["restriction"],
    "region": "France"
  },
  {
    "title": "Municipales 2020 : la participation s’effondre à 38,77% à 17h, le point dans le Sud-Ouest",
    "url": "https://www.sudouest.fr/2020/03/15/municipales-2020-taux-de-participation-18-38-en-forte-baisse-par-rapport-a-2014-7325929-10883.php",
    "published_date": "2020-03-15T12:07:21+01:00",
    "entity": "government",
    "tags": ["democracy"],
    "region": "France"
  },
  {
    "title": "Arrêté du 15 mars 2020 complétant l'arrêté du 14 mars 2020 portant diverses mesures relatives à la lutte contre la propagation du virus covid-19",
    "url": "https://www.legifrance.gouv.fr/eli/arrete/2020/3/15/SSAS2007753A/jo/texte",
    "published_date": "2020-03-15T00:00:00+01:00",
    "entity": "government",
    "tags": ["announcement", "restriction", "economy"],
    "region": "France"
  },
  {
    "title": "Décret n° 2020-260 du 16 mars 2020 portant réglementation des déplacements dans le cadre de la lutte contre la propagation du virus covid-19 (confinement)",
    "url": "https://www.legifrance.gouv.fr/eli/decret/2020/3/16/PRMX2007858D/jo/texte",
    "published_date": "2020-03-16T00:00:00+01:00",
    "entity": "government",
    "tags": ["announcement", "stay-at-home", "restriction"],
    "region": "France"
  },
  {
    "title": "Coronavirus : le groupe de luxe LVMH va fabriquer du gel hydroalcoolique pour le donner aux hôpitaux de Paris",
    "url": "https://www.sudouest.fr/2020/03/16/coronavirus-le-groupe-de-luxe-lvmh-va-fabriquer-du-gel-hydroalcoolique-pour-le-donner-aux-hopitaux-de-paris-7332381-10861.php",
    "published_date": "2020-03-16T12:24:27+01:00",
    "entity": "company",
    "tags": ["announcement", "pledge", "hand-sanitizer"],
    "region": "France"
  },
  {
    "title": "REPLAY. Face au coronavirus, \"nous sommes en guerre\", déclare Emmanuel Macron. Regardez l'intégralité de l'allocution du président de la République",
    "url": "https://www.francetvinfo.fr/sante/maladie/coronavirus/direct-coronavirus-regardez-les-annonces-d-emmanuel-macron-pour-lutter-contre-la-pandemie-de-covid-19_3870001.html",
    "published_date": "2020-03-16T19:40:46+01:00",
    "entity": "government",
    "tags": ["announcement", "stay-at-home"],
    "region": "France"
  },
  {
    "title": "Coronavirus stade 3 : le traitement à la chloroquine efficace, selon le professeur Raoult de l'IHU de Marseille",
    "url": "https://france3-regions.francetvinfo.fr/provence-alpes-cote-d-azur/bouches-du-rhone/marseille/coronavirus-stade-3-traitement-chloroquine-efficace-professeur-raoult-ihu-marseille-1792037.html",
    "published_date": "2020-03-16T20:41:10+01:00",
    "entity": "government",
    "tags": ["treatment"],
    "region": "France"
  },
  {
    "title": "En Alsace, les hôpitaux tentent d'encaisser le choc du coronavirus",
    "url": "https://www.20minutes.fr/strasbourg/2741095-20200316-coronavirus-alsace-40-ans-medecine-jamais-vu-ca-temoigne-chef-service-reanimation-colmar",
    "published_date": "2020-03-16T15:24:18+01:00",
    "entity": "health-organization",
    "tags": ["virus"],
    "region": "France"
  },
  {
    "title": "VRAI OU FAKE Coronavirus : oui, ce texto \"Alerte Covid-19\" a bien été envoyé par le gouvernement (et il en a le droit)",
    "url": "https://www.francetvinfo.fr/sante/maladie/coronavirus/coronavirus-oui-ce-texto-alerte-covid-19-a-bien-ete-envoye-par-le-gouvernement-et-il-en-a-le-droit_3871207.html",
    "published_date": "2020-03-17T16:46:25+01:00",
    "entity": "newspaper",
    "tags": ["announcement", "restriction", "stay-at-home"],
    "region": "France"
  },
  {
    "title": "«La seule solution contre le coronavirus c’est un masque pour tous, partout, pendant trois semaines»",
    "url": "https://www.youtube.com/watch?v=gPMwAcWeUZc",
    "published_date": "2020-03-12T00:00:00+01:00",
    "entity": "individual",
    "tags": ["virus", "mask"],
    "region": "France"
  },
  {
    "title": "CORONAVIRUS:JE VOUS IMPLORE- écrit le 15 mars 2020",
    "url": "https://blogs.mediapart.fr/pierre-jacques-raybaud/blog/160320/coronavirusje-vous-implore-ecrit-le-15-mars-2020",
    "published_date": "2020-03-16T00:32:31+01:00",
    "entity": "individual",
    "tags": ["mask", "stay-at-home", "restriction"],
    "region": "France"
  },
  {
    "title": "Attestation de déplacement : comment l'utiliser avec son iPhone",
    "url": "https://www.igen.fr/iphone/2020/03/attestation-de-deplacement-la-remplir-et-lutiliser-avec-son-iphone-113663",
    "published_date": "2020-03-17CT13:00:00+01:00",
    "entity": "government",
    "tags": ["announcement", "stay-at-home", "restriction"],
    "region": "France"
  },
  {
    "title": "L'attestation de déplacement n'est finalement PAS valable sur smartphone",
    "url": "https://www.igen.fr/ailleurs/2020/03/lattestation-de-deplacement-nest-finalement-pas-valable-sur-smartphone-113687",
    "published_date": "2020-03-18T12:06:00+01:00",
    "entity": "government",
    "tags": ["announcement", "stay-at-home", "turnaround"],
    "region": "France"
  },
  {
    "title": "Coronavirus : les cliniques se mobilisent mais alertent sur le manque de matériel de protection (Les établissements privés promettent 4 000 lits afin de soulager les hôpitaux publics. )",
    "url": "https://www.lemonde.fr/planete/article/2020/03/18/coronavirus-les-cliniques-se-mobilisent-mais-alertent-sur-le-manque-de-materiel-de-protection_6033522_3244.html",
